language: python
python:
    - "2.6"
    - "2.7"
    - "nightly"
addons:
    apt_packages:
        - "swig"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: nosetests
